# Generated by Django 4.2.24 on 2025-09-14 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(help_text='Age in months')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('is_vaccinated', models.BooleanField(default=False)),
                ('is_neutered', models.BooleanField(default=False)),
                ('health_certificate', models.FileField(blank=True, null=True, upload_to='health_certificates/')),
                ('image', models.ImageField(upload_to='dogs/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='dogs/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='dogs/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='dogs/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('pending', 'Pending')], default='available', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs_for_sale', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, help_text='Message to seller', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dogs.dog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='dogs.dog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'dog')},
            },
        ),
        migrations.AddIndex(
            model_name='dog',
            index=models.Index(fields=['breed'], name='dogs_dog_breed_8b76fa_idx'),
        ),
        migrations.AddIndex(
            model_name='dog',
            index=models.Index(fields=['price'], name='dogs_dog_price_2dcc1b_idx'),
        ),
        migrations.AddIndex(
            model_name='dog',
            index=models.Index(fields=['location'], name='dogs_dog_locatio_0d7a39_idx'),
        ),
        migrations.AddIndex(
            model_name='dog',
            index=models.Index(fields=['status'], name='dogs_dog_status_c70e42_idx'),
        ),
    ]
