# Generated by Django 4.2.24 on 2025-09-14 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='fas fa-paw', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Accessory Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('food', 'Food & Treats'), ('toys', 'Toys & Play'), ('health', 'Health & Grooming'), ('safety', 'Safety & Training'), ('bedding', 'Bedding & Comfort'), ('clothing', 'Clothing & Accessories'), ('travel', 'Travel & Outdoor'), ('other', 'Other')], default='other', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accessories/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='accessories/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='accessories/')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessory_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accessories.accessorycategory')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Accessories',
                'ordering': ['-created_at'],
            },
        ),
    ]
